# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/cffc134d-4349-4a41-a5d3-0f279dc2bb7c";
      randomEncryption = true;
    }
  ];

  fileSystems."/" = {
    device = "zpool/root";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/nix" = {
    device = "zpool/nix";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var" = {
    device = "zpool/var";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/home" = {
    device = "zpool/home";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partuuid/1a6d156b-8a3d-4893-8c20-dfaaed32f77f";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  boot.supportedFilesystems = [ "ntfs" ];
  fileSystems."/run/media/thedb/stor dreng" = {
    device = "/dev/disk/by-uuid/94686AF9686AD98E";
    fsType = "ntfs3";
    options = [
      "rw"
      "nosuid"
      "nodev"
      "nofail"
      "relatime"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "uhelper=udisks2"
      "x-gvfs-hide" # Hide unmount button, don't want that happening.
    ];
    neededForBoot = false;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
