# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  
  boot.supportedFilesystems = [ "ntfs" ];
  # I FRIGGIN HATE THE R9 390 !!!!!!!!!!!!!!!!!!!!!
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm" "kvm-intel" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "radeon" ];
  boot.kernelParams = [
    "radeon.cik_support=0"
    "radeon.si_support=0"
    "amdgpu.cik_support=1"
    "amdgpu.si_support=1"
    "amdgpu.dc=1"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/83ddf5fd-8eab-4173-956d-451dccd814b6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4CC7-FD3C";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/run/media/thedb/stor dreng" = {
    device = "/dev/disk/by-uuid/94686AF9686AD98E";
    fsType = "ntfs3";
    options = [
      "rw"
      "nosuid"
      "nodev"
      "relatime"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "uhelper=udisks2"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
